# Generated by Django 3.1.7 on 2021-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(choices=[('CM10', 'Coffee Machine Large'), ('CM00', 'Coffee Machine Small'), ('EM00', 'Espresso Machine')], default='CM00', max_length=4)),
                ('water_line_compatible', models.BooleanField(default=False)),
                ('model', models.CharField(choices=[('1', 'Base'), ('2', 'Premium'), ('3', 'Delux')], default='1', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_type', models.CharField(choices=[('CP0', 'Coffee Pod Small'), ('CP1', 'Coffee Pod Large'), ('EP0', 'Espresso Pod')], default='CP0', max_length=3)),
                ('flavor', models.CharField(choices=[('VANILLA', 'Flavor Vanilla'), ('CARAMEL', 'Flavor Caramel'), ('PSL', 'Flavor Psl'), ('MOCHA', 'Flavor Mocha'), ('HAZELNUT', 'Flavor Hazelnut')], default='VANILLA', max_length=10)),
                ('package_size', models.IntegerField(choices=[(1, '1 Dozen'), (3, '3 Dozen'), (5, '5 Dozen'), (7, '7 Dozen')], default=1)),
            ],
        ),
    ]
